version: '3.8'
volumes:
  appdata:
    name: appdata
  bashhistory:
    name: bashhistory
  dbdata:
    name: dbdata
  esdata:
    name: esdata
  redis:
    name: redis
  sshdirectory:
    name: sshdirectory
  tmp-dbdata:
    name: tmp-dbdata
    driver_opts:
      device: tmpfs
      type: tmpfs
services:
  redis:
    ports:
      - "6379:6379"
    image: docker.io/wardenenv/redis:5.0
  db:
    ports:
      - "3306:3306"
    command:
    - mysqld
    - --max_allowed_packet=1024M
    - --explicit_defaults_for_timestamp=on
    environment:
      MYSQL_DATABASE: magento
      MYSQL_PASSWORD: magento
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_USER: magento
    image: docker.io/wardenenv/mariadb:10.3
    volumes:
    - type: volume
      source: dbdata
      target: /var/lib/mysql
  elasticsearch:
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    image: docker.io/wardenenv/elasticsearch:7.9
    volumes:
    - type: volume
      source: esdata
      target: /usr/share/elasticsearch/data
      volume: {}
  elasticsearch-hq:
    image: elastichq/elasticsearch-hq:latest
    ports:
      - "9300:9300"